[package]
name = "memos"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-identity = "0.6.0"
actix-session = { version = "0.8.0", features = ["cookie-session"] }
actix-web = "4.3.1"
anyhow = "1.0.75"
async-trait = "0.1.74"
hex = "0.4.3"
libsql-client = "0.31.0"
prost = "0.12.3"
prost-types = "0.12.3"
serde = "1.0.193"
serde_json = "1.0.108"
shuttle-actix-web = "0.34.0"
shuttle-runtime = "0.34.0"
shuttle-secrets = "0.34.0"
shuttle-turso = "0.34.0"
sm3 = "0.4.2"
snafu = "0.7.5"
tokio = "1.26.0"
tracing = "0.1.40"
tonic = "0.10.2"
tonic-web = "0.10.2"

[build-dependencies]
protoc-bin-vendored = "3.0.0"
proto-builder-trait = { git = "https://github.com/thlstsul/proto-builder-trait.git", branch = "thlstsul-patch-1", default-features = false, features = ["tonic"] }
tonic-build = "0.10.2"
