# cargo-make

[tasks.run]
install_crate = "cargo-shuttle"
command = "shuttle"
args = ["run"]
dependencies = ["build"]

[tasks.deploy]
install_crate = "cargo-shuttle"
command = "shuttle"
args = ["deploy", "--ad"]
dependencies = ["build"]

[tasks.install]
cwd = "./web"
command = "pnpm"
args = ["install"]

[tasks.build]
cwd = "./web"
command = "pnpm"
args = ["build", "--mode", "release"]
dependencies = ["install"]
