# cargo-make

[tasks.run]
install_crate = "cargo-shuttle"
command = "shuttle"
args = ["run"]
dependencies = ["web-build"]

[tasks.deploy]
install_crate = "cargo-shuttle"
command = "shuttle"
args = ["deploy", "--ad"]
dependencies = ["web-build"]

[tasks.web-install]
cwd = "./web"
script_runner = "@shell"
script = '''
pnpm install
'''

[tasks.web-build]
cwd = "./web"
script_runner = "@shell"
script = '''
pnpm build --mode release
'''
